- trae_agent/cli.py
- trae_agent/utils/config.py
The PR is a follow up PR after noticing the issues that require support of different models. 
where I think we need a more robust way to handle different providers.
This PR handles provider to provider API string function. Instead of just if else I refactor to another function in the config.py file. 
(Sorry my bad I forget to switch to main before opening another branch so a bit duplicated with previous pull request but the content isn't too much so I didn't switch back.)
> Refactor: Provider to Provider API string

- trae_agent/agent/trae_agent.py
This PR addresses a potential issue in the get_git_diff function that could leave the current working directory in an inconsistent state if an invalid project path is provided.
Problem
The function attempts to change the working directory without verifying if the project path is valid.
If the path is invalid or an error occurs during the git diff execution, it can result in unexpected behavior or side effects.
Solution
Validation: Added a check to confirm that the project path is a valid directory before attempting to change to it.
Error Handling: Wrapped the git diff operation in a try...except block to gracefully handle any exceptions.
Impact
Improves robustness and reliability of the get_git_diff function.
Prevents side effects due to invalid directory changes or failed Git operations.
> Fix: Handled invalid project path in get_git_diff

- pyproject.toml
- tests/utils/test_ollama_client_utils.py
- trae_agent/cli.py
- trae_agent/tools/base.py
- trae_agent/utils/config.py
- trae_agent/utils/google_client.py
- trae_agent/utils/llm_client.py
- trae_agent/utils/ollama_client.py
- trae_config.json
- uv.lock
This PR introduces a new `GoogleClient` for interacting with the Google Gemini API, providing full support for chat, tool calling, and other native features. #15 
1.  Added Gemini-specific field `name` for function-calling/tool-calling support.
2.  Added Gemini-specific `candidate_count` parameter.
3.  Added `stop_sequences` parameter that allows users to use tags like `<summary>`, `<thinking>`, etc., in their prompt. Stop_sequences works with gemini models however other models haven't been tested yet.
4.  Integrated `googleClient` with the latest `google-genai` 1.24.0 SDK.
5.  Implemented `call_id` generation for Gemini tool calls to align with Trae's unified `ToolCall` interface, as this is not provided by the native API.
6.  Added a sample config for Google in `trae_config.json`.
> Feature: Gemini Models Support

- trae_agent/tools/edit_tool.py
The `suggested_path` was constructed using `Path("")` which creates a same path as `path`. Should use `Path("/")` to construct an absolute path as suggestion.
/
/
/
> Fix suggested absolute path to start with '/'

- .github/workflows/ci.yml
Currently, the CI workflow is triggered by events (such as `push`) within forked repositories. This leads to unnecessary CI runs, consumes resources.
This PR ensures that the CI pipeline only runs in the context of the origin repository. It will no longer be triggered by activities within forks, but will still run correctly for events like pull requests submitted to this repository.
> ci: Restrict CI execution to the origin repository

- .github/workflows/pre-commit.yml
- .github/workflows/unit-test.yml
- tests/agent/test_trae_agent.py
- tests/tools/test_bash_tool.py
- tests/tools/test_edit_tool.py
- tests/utils/test_ollama_client_utils.py
- tests/utils/test_openrouter_client_utils.py
This PR introduces unit test CI to protect trae-agent, while removing some unnecessary sys.path insertions in current tests.
We can directly run pytest using:
```
uv run pytest tests
```
Currently there are many failed tests, we may need to fix these failed tests first:
```
15 failed, 10 passed in 2.09s
```
> tests: introduce unit test CI and remove unnecessary sys.path insert

- trae_agent/utils/openai_client.py
Added support for o4-mini model
Both "o4-mini" and "o3" models do not support the temperature parameter. currently only for "o3" model the temperature param was not being added to the chat completions, but it was being added for "o4-mini" model. I made the slight change, to do the same for both. It checks if the model is not ("o3" and "o4-mini"), if it is not then temperature parameter is added, else openai.NOT_GIVEN is passed, as it was done before for "o3" model.
Note: since it was a very minor change thus unit tests were not needed
Try running the trae-cli with provider as openai and model as o4-mini (already tested, it works)
ex:
trae-cli run "create a python script to print 'Hello world'" --provider openai --model o4-mini
> Added support for o4-mini model

- README.md
update the readme documentation and warn the user to use the base url. 
This PR is suggested from the issue #64. The purpose is to avoid other using wrong base url. 
N/A
#64
> Doubao base url warning in readme.md

- README.md
- docs/tools.md
This PR adds a separate documentation for tools at ```docs/tools.md```. Tools description in ```REAMDE.md``` is replaced by a concise description of tools.
> feat(docs): added seperate docs/tools.md and placeholder in readme.md

- README.md
- sdk/python/_run.py
- tests/utils/test_config.py
- trae_agent/cli.py
- trae_agent/utils/anthropic_client.py
- trae_agent/utils/azure_client.py
- trae_agent/utils/config.py
- trae_agent/utils/doubao_client.py
- trae_agent/utils/google_client.py
- trae_agent/utils/ollama_client.py
- trae_agent/utils/openai_client.py
- trae_agent/utils/openrouter_client.py
The fix comes from a bug report, where Doubao api key and base url are set, but when calling the model, it uses the 'doubao_base_url' as the base_url, which comes from the default settings.
In addition, currently, all clients have same code to read API keys and URLs from the env, which should be done during configuration.
All tests passed.
Online report.
> Bugfix: reoganise configuration settings

- trae_agent/utils/ollama_client.py
This pull request addresses the issue where the agent becomes unresponsive when connecting to the local ollama client.
> fix(ollama): repair ollama client config

- pyproject.toml
fix: add missing socksio dependency for SOCKS proxy support
Resolves ImportError on macOS when using SOCKS proxy with httpx. Users can now run `uv sync --all-extras` to install all dependencies.
Added `socksio` as a project dependency to fix ImportError that occurs when the application attempts to use SOCKS proxy functionality through httpx transport layer. This dependency was missing from the project configuration, causing the anthropic client initialization to fail on macOS systems.
The error was occurring in the httpx transport initialization when creating an Anthropic client with SOCKS proxy settings. The `socksio` package is required by httpx for SOCKS proxy support, but it's an optional dependency that wasn't included in our project's dependency list.
Changes made:
- Added `socksio` …
> fix: add missing socksio dependency for SOCKS proxy support

- evaluation/swebench.py
- tests/test_cli.py
- trae_agent/cli.py
This PR introduces fix for #150. With these changes,
1) ```trae-cli run "..." ``` will always treat the input as a literal task string, regardless of its length or content.
2) To run a task from a file, the user must now use the new explicit ```--file``` flag: 
```trae-cli run --file /path/to/task.txt.```
The cli is able to handle long prompts now. I have also included 8 tests for ```cli.py``` covering edge cases that I could think of.
```
1) test_run_with_long_prompt
2) test_run_with_file_argument
3) test_run_with_nonexistent_file
4) test_run_with_both_task_and_file
5) test_run_with_no_input
6) test_run_with_nonexistent_working_dir
7) test_run_with_string_that_is_also_a_filename
8) test_run_handles_agent_exception
```
> fix(cli): handles long prompt error and explicit --file flag with tests for cli.

- trae_agent/utils/openai_client.py
- trae_agent/utils/openrouter_client.py
- trae_agent/utils/retry_utils.py
This pull request fixes a misleading error message that always printed `OpenAI API call failed` during retry attempts, even when the actual provider was different (e.g. `openrouter`). The message now dynamically reflects the actual provider being used.
`retry_with` in `retry_utils.py` now accepts a `provider_name` parameter.
The log message inside `retry_with` was updated to use this dynamic value:
```python
print(f"{provider_name.capitalize()} API call failed: {this_error_message} will sleep for {sleep_time} seconds and will retry.")
```
`OpenRouterClient` and `OpenAIClient` were updated to pass the correct `provider_name` when initializing the retry decorator:
```python
retry_decorator = retry_with(
func=self._create_openrouter_response,
max_retries=model_parameters.max_retries, …
```
> Fix: Use correct provider name in retry error logs

- Makefile
- README.md
sync Makefile and README commands for development setup
- Add install-dev target to Makefile for one-step environment setup
- Update README contributing guide to use install-dev command
- Fix pre-commit commands in README to match actual Makefile targets
- Add ruff formatting commands as fallback for formatting errors
- Ensure documentation consistency between Makefile and README
This change simplifies the development setup process by providing
a single command (make install-dev) that creates virtual environment
and installs all dependencies, making it easier for new contributors
to get started with the project.
> fix:Organize Makefile and related documentation

- evaluation/swebench.py
Allow users to locally modify the agent source code when validating with swebench.py
The current swebench.py clones https://github.com/bytedance/trae-agent.git into the docker, making it impossible for users to modify the agent. This PR changes the behavior to copying the current directory into the docker, hence preserving local changes.
Run swebench.py
None
> feat: build from source in swebench script

- trae_agent/utils/ollama_client.py
This pull request fixes a runtime error occurring when using Ollama with tool calls. The bug originated from assuming that every `tool_call` object returned by the Ollama API would contain a `.type` attribute. However, some responses lack this field, causing the following exception:
```bash
AttributeError: 'ToolCall' object has no attribute 'type'
```
The logic has now been updated to safely check the structure of `tool_call` objects using `hasattr(...)` before accessing attributes like `type`, `content`, etc.
```python
for output_block in response.message.tool_calls:
if output_block.type == "function_call":  # This causes AttributeError if 'type' is missing
```
```python
for output_block in response.message.tool_calls:
if hasattr(output_block, "name") and hasattr(output_block, …
```
> fix(ollama): avoid AttributeError by safely handling missing 'type' in tool call responses

- trae_agent/tools/bash_tool.py
Add newline before command separator.
Some models may use heredoc, such as
```bash
python - << 'EOF'
... (some python code here)
EOF
```
The last line needs to be exact the delimiter w/o other symbols.
> add newline before command separator

- trae_agent/utils/ollama_client.py
According to #207 currently it doesn't support qwen3:4b. Noticing it is not added it into supports_tool_calling. 
N/A
N/A
#207
> [DEBUG]: Support Qwen:4b model

- trae_agent/utils/openai_client.py
- trae_agent/utils/openrouter_client.py
- trae_agent/utils/retry_utils.py
The `service_name` variable is defined but was previously not used in the function, while `provider_name` is currently used but is typically set to the default value "unknown" because most references only pass `service_name`.
To minimize changes and improve clarity, this PR removes `provider_name` and uses only `service_name`.
> fix: remove unused variable

- tests/tools/test_bash_tool.py
- trae_agent/agent/base_agent.py
- trae_agent/tools/base.py
- trae_agent/tools/bash_tool.py
- The `stop` method of class `_BashSession` only executed `self._process.terminate`, which was insufficient to fully release the resources of `self._process`.  
- Added the `_close_tools` method in `BaseAgent`, executed within the `execute_task` method, ensuring graceful task termination and eliminating error message output in **windows** after task completion.  
None
- On Ubuntu 22.04.5 LTS, the submitted code has passed all test cases . Verified by running `make test`, got 62 passed, 17 skipped, 1 warning on Linux, 
- On Windows 10 since I don't have `make` installed, the submitted code has passed 2 real programming cases and 1 EXCEPTION case (The task is not completed when the maximum steps are reached first).
- The submitted code has passed `flake8` linting, with all newly introduced …
> Fix: fix the `_BashSession.stop` to completely release resources and ensure graceful task completion in Windows

- server/Readme.md
This is a PR that creates the roadmap for handling the HTTP server. 
@chao-peng, we need to decide which framework to use for hosting this HTTP server. Two common libraries are Flask and FastAPI.
N/A
N/A
#250
> HTTP-Server Roadmap
