bytedance/trae-agent

- README.md
- trae_agent/cli.py
- trae_agent/utils/llm_client.py
- trae_agent/utils/openrouter_client.py
- trae_config.json
This pull request introduces support for OpenRouter as an additional LLM provider. It also includes updates to the CLI, configuration handling, and documentation to support this integration and improve overall maintainability.
* Added OpenRouter to the `LLMProvider` enum.
* Implemented a dedicated client wrapper for OpenRouter in `llm_client.py`.
* Introduced new environment variables for configuring OpenRouter (e.g., `OPENROUTER_API_KEY`, `OPENROUTER_MODEL`).
* Refactored `run`, `interactive`, and `show_config` commands for better readability and structure.
* Added support for OpenRouter-specific options in the configuration loading logic.
* Improved error handling and CLI output formatting.
* Updated `README.md` with setup instructions for OpenRouter.
* Added example usage and list of …
> feat(openrouter): add OpenRouter support 

- trae_agent/cli.py
Inline documentation is very important for further development. This PR is for sack of providing documentation for cli.py. It is believed that there will be no any error after merging this PR.
> Comment Documentation to cli.py

- trae_agent/agent/trae_agent.py
This PR handle the issue number #13 resolving the typo from 
totalThoughs to total_thoughts which should be the correct one.
> Debug: Typo Issue trae_agent.py

- tests/utils/test_ollama_client_utils.py
- trae_agent/agent/trae_agent.py
- trae_agent/tools/base.py
- trae_agent/tools/bash_tool.py
- trae_agent/tools/edit_tool.py
- trae_agent/tools/sequential_thinking_tool.py
- trae_agent/tools/task_done_tool.py
- trae_agent/utils/ollama_client.py
- trae_agent/utils/openai_client.py
This PR introduces fixes tool calling with openAI (#19) and is thoroughly tested with gpt-4o and o3. Highlight suggestion would be to incorporate a custom prompt for o3. 
1. In trae_agent.py, the tools are now correctly configured for the LLM provider in use. 
2. In trae_agent.py the system prompt has been updated for the LLM to strictly use the provided project path and not assume ```/repo``` or ```/workspace``` directory. I did this cause o3 was hallucinating on the project path. Either incorporating this change
into the system prompt or a seperate system prompt tailored towards o3 would be great
3. In ```tools/base.py```, ```schema["additionalProperties"] = False``` has been added to make sure extra properties aren't allowed in the input schema. The OpenAI client strictly requires this …
> Agent supports OpenAI models. Tested with gpt-4o and o3.

- tests/utils/test_ollama_client_utils.py
- trae_agent/utils/ollama_client.py
This PR handle ruff formatting problem that happens during the pre commit. 
One should note that we have to run both 
```
ruff format . 
ruff check --fix .
```
before git add and git commit. 
I tested with my forked repo and works well. 
N/A
> Debug: CI ruff formating problem

- CONTRIBUTING
- README.md
Add instructions to properly setup the development environment
> Doc(develop): update the devlopment environment setup instruction

- trae_agent/agent/agent_basics.py
Refactors the agent.py module to improve readability, maintainability, and developer experience. Specifically, this change:
Replaces verbose | None type hints with Optional[...] for clarity
Expands docstrings for all major classes to clarify their role
Adds __repr__ methods to improve logging and debugging output
Defines __all__ to explicitly declare the module's public API
These improvements are non-functional and do not change behavior. They are meant to improve the overall developer ergonomics of working with the agent system.
This change is useful for:
Making the codebase easier to understand for new contributors
Improving the quality of logs during multi-step agent executions
Providing stronger static typing for IDEs and type checkers (e.g., mypy)
Clarifying the role and purpose of …
> Refactor agent module: clearer type hints, docstrings, and debugging support

- CONTRIBUTING
- Makefile
- README.md
- tests/agent/test_trae_agent.py
- tests/utils/test_config.py
- trae_agent/agent/agent_basics.py
- trae_agent/tools/json_edit_tool.py
- trae_agent/utils/config.py
- trae_agent/utils/openai_client.py
- trae_agent/utils/openrouter_client.py
* Created Makefile with install, pre-commit, and test commands.
* Fixed several linting and testing errors.
* Update README and CONTRIBUTION accordingly.
N/A
```
make test
```
All tests paased.
N/A
> Makefile with useful commands

- README.md
This PR adds google/gemini client information to the ```README.md```
> Modify README.md to reflect google client

- README.md
- docs/TRAJECTORY_RECORDING.md
Hotfix for a recent linter error
> fix linter error

- .github/workflows/unit-test.yml
- tests/utils/test_google_client.py
This PR introduces unit tests for the google client.
> feat(google-client): added nine comprehensive tests for google client

- tests/tools/test_bash_tool.py
> chore: remove some chinese

- .github/workflows/pre-commit.yml
- .github/workflows/unit-test.yml
- Makefile
Make the developer experience consistent with CI
> chore: update workflow to using makefile

- evaluation/swebench.py
- evaluation/swebench_setup.sh
修复了SWE-bench评估脚本中的参数传递错误和shell语法错误，确保评估流程能够正常运行。
1. **参数传递错误**：在 `evaluation/swebench.py` 的 `run_all()` 方法中，`run_one_instance()` 方法调用时传递了错误的参数。原代码传递了整个 `instance` 对象，但该方法期望接收 `instance_id` 字符串参数。
2. **Shell语法错误**：在 `evaluation/swebench_setup.sh` 中，`SWE_BENCH_COMMIT_HASH` 变量的赋值语法不正确，缺少了等号两边的空格。
- **evaluation/swebench.py**: 将 `self.run_one_instance(instance)` 改为 `self.run_one_instance(instance["instance_id"])`
- **evaluation/swebench_setup.sh**: 将 `SWE_BENCH_COMMIT_HASH = "..."` 改为 `SWE_BENCH_COMMIT_HASH="..."`
这些错误会导致：
- SWE-bench评估运行时出现参数类型错误，导致评估失败
- Shell脚本执行时出现语法错误，无法正确设置SWE-bench环境
修复后评估脚本可以正常运行，确保SWE-bench评估流程的稳定性。
可以通过以下方式验证修复效果：
1. **检查shell脚本语法**：
```bash
bash -n evaluation/swebench_setup.sh
```
2. **运行SWE-bench评估**：
```bash
python evaluation/swebench.py --mode=expr …
```
> fix: evaluation swebench params

- trae_agent/tools/edit_tool.py
Currently edit_tool.py execute function is quite nested. Some refactor is necessary to make sure the code is clean. 
N/A
Tested with Openrouter and works. 
N/A
> Refactor: refactor edit_tool.py with handler

- trae_agent/agent/trae_agent.py
- trae_agent/prompt/agent_prompt.py
Extract the system prompt more easily for running the experiment.
N/A
N/A
N/A
> Refactor: Refactor System prompt

- trae_agent/utils/openrouter_client.py
Refactor open router parse message function. 
Just refactor to some private function. The code looks cleaner after refactor. 
Works with open router client locally. 
#78
> Refactor: Refactor Open router parse message function

- trae_agent/tools/edit_tool.py
Edit tool insert and view function is not called outside edit_tool.py so should be a private function. 
N/A
N/A
N/A
> Refactor: Refactor some methods to Private Method

- README.md
Add trae discord community to the readme file. 
Would you kindly enable the widget for the Discord server Thanks ! 
N/A
N/A
> Docs: Readme.md update discord link

- trae_agent/prompt/agent_prompt.py
- trae_agent/tools/json_edit_tool.py
This PR fixes #163. It enhances the system prompt and doesn't face 
```
{
"timestamp": "2025-07-13T00:43:46.775567",
"provider": "google",
"model": "gemini-2.5-flash",
"input_messages": [
{
"role": "user",
"content": null,
"tool_result": {
"call_id": "5dfa66e6-a39d-4188-b48d-451dfd4cf897",
"success": false,
"result": null,
"error": "File path must be absolute: test.json",
"id": null
}
}
],
```
and needs to waste an extra step on resolving this increasing its cognitive load. I have tried these changes several times and it has now stopped facing this step and oneshots the file path all the time. Test this out and let me know if it works for yall. Can enhance and make more changes if necessary. Thanks!
> fix(agent): fixed absolute path handling with robust system prompt.

- trae_agent/utils/anthropic_client.py
- trae_agent/utils/azure_client.py
- trae_agent/utils/doubao_client.py
- trae_agent/utils/google_client.py
- trae_agent/utils/ollama_client.py
- trae_agent/utils/openai_client.py
- trae_agent/utils/openrouter_client.py
- trae_agent/utils/retry_utils.py
This change refactors duplicate retry logic across all model clients into a unified `retry_utils` module, replacing manual retry loops with a decorator pattern for better code reusability and consistency.
> Refactor: unify error retry logic across all model clients

- trae_agent/db/ckg.py
- trae_agent/db/db.py
- trae_agent/tools/ckg_tool.py
Refactor ckg_tool to multiple part especially refactor to db folder .
(Sorry this PR is a bit long PTAL)
Run with open router and it works. Yet it would be way better if we can have some unit test cases.
#171
> Refactor: Refactor CKG tool to Database

- trae_agent/tools/base.py
This PR fixes #165. This introduces normalization of tool call names so the agent never wastes one of their steps on finding the right tool name such as
```
"tool_calls": [
{
"call_id": "745afaee-9616-408a-9cd5-3a0981e3af33",
"name": "sequential_thinking",
"arguments": {
"next_thought_needed": true,
"thought_number": 1,
"thought": "The user wants to read the \"theme\" property from the \"config\" object in `test.json` and then add a \"theme_preference\" property to the user with ID 2, setting its value to the read theme. I will use the `json_edit_tool` to first view the theme and then set the new property.",
"total_thoughts": 3
},
"id": null
}
]
},
"tools_available": [
"str_replace_based_edit_tool",
"sequentialthinking",
"json_edit_tool",
"task_done",
"bash"
]
},
{
"timestamp": …
```
> fix(agent): normalized tool calling

- trae_agent/agent/base.py
- trae_agent/utils/cli_console.py
This PR fixes an indefinite loop problem introduced by a previous code refactoring and made the following improvements:
- Simplify lakeview config check by combining conditions
- Move step creation logic into _run_llm_step for better clarity
- Remove redundant methods and inline their functionality
- Improve error handling by directly finalizing steps on exceptions
Resolves #228
> Fix the indefinite loop problem

- trae_agent_rs/core/src/tools/bash.rs
Add test for bash tool. 
Add unit test. 
```bash
test result: ok. 72 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.00s
Doc-tests trae_core
running 3 tests
test core/src/llm/llm_client.rs - llm::llm_client::LLMClient::new (line 176) ... FAILED
test core/src/llm/llm_client.rs - llm::llm_client (line 11) ... FAILED
test core/src/llm/llm_client.rs - llm::llm_client::LLMClient::chat (line 241) ... FAILED
```
N/A
> add bash test

- trae_agent_rs/core/src/lib.rs
- trae_agent_rs/core/src/trajectories/mod.rs
- trae_agent_rs/core/src/trajectories/trajectories.rs
Provide the trajectory with rust
N/A
```
test result: ok. 61 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s
Doc-tests trae_core
running 3 tests
test core/src/llm/llm_client.rs - llm::llm_client::LLMClient::new (line 176) ... FAILED
test core/src/llm/llm_client.rs - llm::llm_client (line 11) ... FAILED
test core/src/llm/llm_client.rs - llm::llm_client::LLMClient::chat (line 241) ... FAILED
```
N/A
> Dev: Trajectory Feature with Rust

- trae_agent_rs/core/examples/openai_compatible_test.rs
- trae_agent_rs/core/examples/trae_agent_test.rs
- trae_agent_rs/core/src/agent/base_agent.rs
- trae_agent_rs/core/src/agent/trae.rs
- trae_agent_rs/core/src/llm/anthropic_client.rs
- trae_agent_rs/core/src/llm/llm_client.rs
- trae_agent_rs/core/src/llm/llm_provider.rs
- trae_agent_rs/core/src/llm/openai_client.rs
- trae_agent_rs/core/src/llm/openai_compatible_client.rs
- trae_agent_rs/core/src/tools/base.rs
- trae_agent_rs/core/src/tools/bash.rs
- trae_agent_rs/core/src/tools/edit.rs
- trae_agent_rs/core/src/tools/mod.rs
Develope and debug the rust agent. 
N/A
N/A
N/A
> Rust Dev: Handle new task function and Debug Agent

- trae_agent_rs/core/examples/trae_agent_test.rs
- trae_agent_rs/core/src/agent/base_agent.rs
- trae_agent_rs/core/src/agent/trae.rs
- trae_agent_rs/core/src/llm/llm_basics.rs
- trae_agent_rs/core/src/trajectories/trajectories.rs
Some basic refactor and update the test case. Trying to integrate the trajectory with Trae Agent
N/A
N/A
N/A
> Refactor part of the trajectory for further development
